version: '3'
services:
  app:
    container_name: docker-angular-node
    restart: always
    build: 
      context: ./guaranity-ide
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
  servertest:
    container_name: server-test
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'